version: '2.1'

services:
  influxdb:
    image: influxdb:2.7.0
    ports:
      - 8086:8086
    volumes:
      - $PWD/influxdb-data/data:/var/lib/influxdb2
      - $PWD/influxdb-data/config:/etc/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=adminadmin
      - DOCKER_INFLUXDB_INIT_ORG=solar-watch
      - DOCKER_INFLUXDB_INIT_BUCKET=solar-data
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=top-secret-auth-token
    networks:
      - my-network

  grafana:
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    links:
      - influxdb
    volumes:
      - ./grafana/provisioning/:/etc/grafana/provisioning
      - ./grafana/custom.ini:/etc/grafana/grafana.ini
    environment:
      GF_INSTALL_PLUGINS: grafana-simple-json-datasource
    networks:
      - my-network

networks:
  my-network:
    name: solar-watch-network
