apiVersion: 1

datasources:
  - name: InfluxDB_v2_Flux
    type: influxdb
    access: proxy
    url: http://raspberrypi.local:8086
    jsonData:
      version: Flux
      organization: solar-watch
      defaultBucket: solar-data
      tlsSkipVerify: true
    secureJsonData:
      token: top-secret-auth-token
