{
 "title": "Solar Watch",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "Battery Voltage",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"solar-data\")\n    |> range(start:-5m)\n    |> filter(fn: (r) => r._field== \"vbattery1\")\n"
    }
   ]
  },
  {
   "title": "Battery Current",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"solar-data\")\n    |> range(start:-5m)\n    |> filter(fn: (r) => r._field== \"ibattery1\")\n"
    }
   ]
  },
  {
   "title": "Battery Power",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"solar-data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._field== \"pbattery1\")\n  \n"
    }
   ]
  },
  {
   "title": "Battery SOC",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 2, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"solar-data\")\n  |> range(start:-5m)\n  |> filter(fn: (r) => r._field== \"battery_soc\")\n"
    }
   ]
  },
  {
   "title": "Production/Export/Import",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "query": "import \"date\"\n\nfrom(bucket: \"solar-data\")\n    |> range(start: date.sub(from: today(), d: 7d))\n    |> filter(fn: (r) => r._field== \"e_day\")\n    |> aggregateWindow(every: 1d, offset: -2h, fn: last)\n    |> truncateTimeColumn(unit: 1m)\n\n"
    },
    {
     "query": "import \"date\"\n\nfrom(bucket: \"solar-data\")\n  |> range(start: date.sub(from: today(), d: 7d))\n  |> filter(fn: (r) => r[\"_field\"] == \"meter_e_total_exp\")\n  |> aggregateWindow(every: 1d, offset: -2h, fn: last)\n  |> difference()\n  |> truncateTimeColumn(unit: 1m)"
    },
    {
     "query": "import \"date\"\n\nfrom(bucket: \"solar-data\")\n  |> range(start: date.sub(from: today(), d: 7d))\n  |> filter(fn: (r) => r[\"_field\"] == \"meter_e_total_imp\")\n  |> aggregateWindow(every: 1d, offset: -2h, fn: last)\n  |> difference()\n  |> truncateTimeColumn(unit: 1m)"
    }
   ]
  },
  {
   "title": "Power",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 13, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "query": "from(bucket: \"solar-data\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r._field== \"ppv\" or r._field== \"house_consumption\" or r._field== \"meter_active_power_total\" or r._field== \"pbattery1\" or r._field== \"battery_soc\")\n"
    }
   ]
  },
  {
   "title": "Production Today",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"solar-data\")\n    |> range(start:-1h)\n    |> last()\n    |> filter(fn: (r) => r._field== \"e_day\")\n"
    }
   ]
  },
  {
   "title": "Production Total",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 3, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"solar-data\")\n    |> range(start: today())\n    |> filter(fn: (r) => r._field== \"e_total\")\n"
    }
   ]
  }
 ]
}